FROM ruby:3.4.8
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \
  && apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs vim \
  && npm install --global yarn
RUN mkdir /myapp
WORKDIR /myapp
RUN gem install bundler
COPY . /myapp