name: Deploy

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  deploy:
    if: github.event.pull_request.merged == true # マージされたら実行
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -fsSL --max-time 300 -X POST "$deploy_url"
